[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_SITE_URL = "https://resistance-lab.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
